// <auto-generated />
using System;
using AdditiveIndex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdditiveIndex.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426144245_AddProductAndRelation")]
    partial class AddProductAndRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("AdditiveIndex.Api.Models.Entities.Additive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ECode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificReferences")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ECode")
                        .IsUnique();

                    b.ToTable("Additives");
                });

            modelBuilder.Entity("AdditiveIndex.Api.Models.Entities.AdditiveProduct", b =>
                {
                    b.Property<int>("AdditiveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdditiveId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("AdditiveProducts");
                });

            modelBuilder.Entity("AdditiveIndex.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("AdditiveIndex.Api.Models.Entities.AdditiveProduct", b =>
                {
                    b.HasOne("AdditiveIndex.Api.Models.Entities.Additive", "Additive")
                        .WithMany("AdditiveProducts")
                        .HasForeignKey("AdditiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdditiveIndex.Api.Models.Entities.Product", "Product")
                        .WithMany("AdditiveProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Additive");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdditiveIndex.Api.Models.Entities.Additive", b =>
                {
                    b.Navigation("AdditiveProducts");
                });

            modelBuilder.Entity("AdditiveIndex.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("AdditiveProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
